### ISSUE TITLE
Trouble connecting PersistentVolume/Claim to ElasticJob

### ISSUE THREAD

**Issue by SeanNaren** [pytorch/elastic#112]
Hey guys!

Use case here is to create a disk, populate it with data, and then in ReadWriteOnce mode connect it to the ElasticJob using k8 configs. To extend this, I'd like to move from ReadWriteOnce to ReadOnlyMany to act as a datastore that all nodes can read the dataset from!

Unfortunately it seems after populating the disk, the ElasticJob comes back with a `persistentvolumeclaim "audio-data-claim" not found` error message. With an non-elastic job I can see the disk has been populated and mounted.

I'm using GKE for this!

### Configs

storage.yaml
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
provisioner: pd.csi.storage.gke.io
metadata:
  name: storage
parameters:
  type: pd-ssd
  fstype: ext4
  replication-type: none
```

persistent_volume.yaml
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audio-data
spec:
  storageClassName: "storage"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: audio-data
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audio-data-claim
spec:
  storageClassName: "storage"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
```

transfer_data.yaml
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: transfer-data
spec:
  containers:
    - image: seannaren/deepspeech.pytorch
      imagePullPolicy: Always
      name: deepspeech
      command: ["python"]
      args:
        - "/workspace/deepspeech.pytorch/data/an4.py"
        - "--target-dir=/audio-data/an4_dataset/"
        - "--manifest-dir=/audio-data/an4_manifests/"
      volumeMounts:
        - mountPath: /audio-data/
          name: audio-data
  restartPolicy: Never
  volumes:
    - name: audio-data
      persistentVolumeClaim:
        claimName: audio-data-claim
```

train.yaml
```yaml
apiVersion: elastic.pytorch.org/v1alpha1
kind: ElasticJob
metadata:
  name: deepspeech
  namespace: elastic-job
spec:
  # Use "etcd-service:2379" if you already apply etcd.yaml
  rdzvEndpoint: "etcd-service:2379"
  minReplicas: 1
  maxReplicas: 1
  replicaSpecs:
    Worker:
      replicas: 1
      restartPolicy: ExitCode
      template:
        apiVersion: v1
        kind: Pod
        spec:
          containers:
            - name: deepspeech
              image: seannaren/deepspeech.pytorch
              imagePullPolicy: Always
              command: ["python", "-m", "torchelastic.distributed.launch"]
              args:
                - "--nproc_per_node=1"
                - "/root/deepspeech.pytorch/train.py"
                - "data.train_manifest=/audio-data/an4_manifests/an4_train_manifest.csv"
                - "data.val_manifest=/audio-data/an4_manifests/an4_val_manifest.csv"
                - "data.num_workers=8"
                - "training.epochs=70"
                - "data.batch_size=8"
                - "checkpointing.save_folder=/audio-data/models/"
              resources:
                limits:
                  nvidia.com/gpu: 1
              volumeMounts:
                - mountPath: /audio-data/
                  name: audio-data
                  readOnly: true
          volumes:
            - name: audio-data
              persistentVolumeClaim:
                claimName: audio-data-claim
                readOnly: true
```

### Commands

```
gcloud container clusters create torchelastic \
    --accelerator type=nvidia-tesla-v100,count=1\
    --machine-type=n1-standard-4 \
    --disk-size=25Gi \
    --zone=us-west1-b \
    --cluster-version=1.15 \
    --preemptible \
    --num-nodes=1

# Within torch elastic/kubernetes repo...
kubectl apply -k config/default
kubectl apply -f https://raw.githubusercontent.com/pytorch/elastic/master/kubernetes/config/samples/etcd.yaml

gcloud compute disks create --size 10Gi audio-data --zone us-west1-b
kubectl apply -f storage.yaml
kubectl apply -f persistent_volume.yaml

kubectl apply -f transfer_data.yaml
## Once finished transferring by checking kubectl logs transfer-data
kubectl delete -f transfer_data.yaml

kubectl apply -f train.yaml # This fails
```

However running this shows that the disk has been populated when checking the logs:

check_storage.yaml
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: check-storage
spec:
  containers:
    - image: seannaren/deepspeech.pytorch
      imagePullPolicy: Always
      name: deepspeech
      command: ["/bin/ls"]
      args:
        - "/audio-data/"
      volumeMounts:
        - mountPath: /audio-data/
          name: audio-data
  restartPolicy: Never
  volumes:
    - name: audio-data
      persistentVolumeClaim:
        claimName: audio-data-claim
```

Any help would be appreciated!

EDIT: I've tried both removing and adding the readOnly flag and it doesn't fix the issue
