### ISSUE TITLE
Pytorch Lightning with TorchElastic - One worker doesn't start

### ISSUE THREAD

**Issue by tchaton** [pytorch/elastic#135]
## 🐛 Bug

Component (check all that applies):
 * [ ] `state api`
 * [ ] `train_step api`
 * [ ] `train_loop`
 * [ ] `rendezvous`
 * [ ] `checkpoint`
 * [ ] `rollback`
 * [ ] `metrics`
 * [ ] `petctl`
 * [ ] `examples`
 * [ ] `docker`
 * [ ] other
 
## To Reproduce

Somehow, one of the worker doesn't start. Any idea what is wrong ?

<img width="1404" alt="Screenshot 2020-11-16 at 21 29 37" src="https://user-images.githubusercontent.com/12861981/99310501-07038580-2853-11eb-8e68-a204a53588ba.png">
<img width="1417" alt="Screenshot 2020-11-16 at 21 28 46" src="https://user-images.githubusercontent.com/12861981/99311013-cb1cf000-2853-11eb-9f1a-2ce3a3d4238b.png">

```
apiVersion: elastic.pytorch.org/v1alpha1
kind: ElasticJob
metadata:
  name: s-9670336-3-7-1-5-e
  namespace: elastic-job
spec:
  # Use "etcd-service:2379" if you already apply etcd.yaml
  rdzvEndpoint: etcd://10.100.165.225:2379/s-9670336-3-7-1-5-e
  minReplicas: 2
  maxReplicas: 2
  replicaSpecs:
    Worker:
      replicas: 2
      restartPolicy: ExitCode
      template:
        apiVersion: v1
        kind: Pod
        spec:
          containers:
            - name: s-9670336-3-7-1-5-e
              image: pytorchlightning/pytorch_lightning:base-cuda-py3.7-torch1.5
              imagePullPolicy: Always
              command: 
              - bash 
              - -ce
              - | 
                git clone https://github.com/tchaton/pytorch-lightning.git /repo
                cd /repo
                git fetch --all
                git checkout 9670336
                pip install -e .
                pip install torchelastic
                python -m torchelastic.distributed.launch --nproc_per_node=1 --rdzv_id=s-9670336-3-7-1-5-e --rdzv_backend=etcd --rdzv_endpoint=10.100.165.225:2379 ./multi_node_tests/test_multi_nodes_gpu.py --num_nodes=2 --gpus=1 --accelerator=ddp --max_epochs 2
              resources:
                limits:
                  nvidia.com/gpu: 1
```

```
import sys
import os
ROOT = os.path.join(os.path.dirname(os.path.realpath(__file__)), "..")
sys.path.insert(0, ROOT)
DIR_PATH = os.path.dirname(os.path.realpath(__file__))
import torch
from argparse import ArgumentParser
import pytorch_lightning as pl
from torch.nn import functional as F
from torch.utils.data import DataLoader, random_split
from pytorch_lightning import LightningModule
from torch.utils.data import Dataset
from tests.base.boring_model import *

def cli_main():
    pl.seed_everything(1234)

    # ------------
    # args
    # ------------
    parser = ArgumentParser()
    parser.add_argument('--batch_size', default=32, type=int)
    parser = pl.Trainer.add_argparse_args(parser)
    args = parser.parse_args()

    model = BoringModel()

    trainer = pl.Trainer.from_argparse_args(args)
    trainer.fit(model)

if __name__ == '__main__':
    cli_main()

```

1.
1.
1.

## Environment

 - torchelastic version (e.g. 0.1.0rc1):
 - OS (e.g., Linux):
 - How you installed torchelastic (`conda`, `pip`, source, `docker`):
 - Docker image and tag (if using docker):
 - Build command you used (if compiling from source):
 - Git commit (if installed from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Execution environment (on-prem, aws, etc):
 - Any other relevant information:
